### ISSUE TITLE
[question] what's the difference between Duplicate and Generate UUID?

### ISSUE THREAD

**Issue by robsonpeixoto** [arenchen/vscode-uuid-generator#3]
What's the use-case for Duplicate a UUID?

**Comment by arenchen** [comment]
you can try these on multi lines

https://user-images.githubusercontent.com/1442240/150625946-99018bd1-bde5-4136-a503-2d20f5acf1ac.mov

maybe u have good naming?

**Comment by robsonpeixoto** [comment]
Thanks! It is really useful!
Maybe `Generate UUID At Cursor` and `Repeat UUID At Cursor`.
